### ISSUE TITLE
Provide more general explanation of what the protocol is for

### ISSUE THREAD

**Issue by sr320** [grace-ac/paper-pacific.oyster-larvae#1]
https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/protocols/01-EncyclopeDIA-protocol.md 

in the file itself (top)

**Comment by grace-ac** [comment]
![Screen Shot 2019-03-27 at 12 13 09 PM](https://user-images.githubusercontent.com/14934314/55105505-ef79f680-5089-11e9-9a8d-9c1998ff6695.png)
