### ISSUE TITLE
Make image urls local paths

### ISSUE THREAD

**Issue by sr320** [grace-ac/paper-pacific.oyster-larvae#3]
@ https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/protocols/01-EncyclopeDIA-protocol.md

and generally make sure urls are not called for images..

we should print to pdf occasionally

**Comment by grace-ac** [comment]
made image links local paths in [01-EncyclopeDIA-protocol.md](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/protocols/01-EncyclopeDIA-protocol.md) and [02-SkylineDaily-protocol.md](https://github.com/grace-ac/paper-pacific.oyster-larvae/blob/master/protocols/02-SkylineDaily-protocol.md)

there are no images in MSStats protocol, and the 4th protocol for blast and Go terms is in progress.
